language: java

jdk:
- oraclejdk8

python:
  - "3.6"

before_install:
- pip3.6 install pyro4
- pip3.6 install git+https://github.com/cta-observatory/pyhessio
- pip3.6 install git+https://github.com/cta-observatory/ctapipe-extra
- pip3.6 install git+https://github.com/cta-observatory/ctapipe
- pip3.6 install numpy
- pip3.6 install astropy
