language: java

jdk:
- oraclejdk8

python:
  - "3.5"

before_install:
- pip36 install pyro4
- pip36 install git+https://github.com/cta-observatory/pyhessio
- pip36 install git+https://github.com/cta-observatory/ctapipe-extra
- pip36 install git+https://github.com/cta-observatory/ctapipe
- pip36 install numpy
- pip36 install astropy
