language: java

jdk:
- oraclejdk8

python:
  - "3.5"

before_install:
- pip install pyro4
- pip install git+https://github.com/cta-observatory/pyhessio
- pip install git+https://github.com/cta-observatory/ctapipe-extra
- pip install git+https://github.com/cta-observatory/ctapipe
- pip install numpy
- pip install astropy
