language: python
 python:
   - "3.6"

addons:
  apt:
    packages:
      - oracle-java8-set-default
      - maven3

script: mvn test

before_install:
- pip install pyro4
- pip install git+https://github.com/cta-observatory/pyhessio
- pip install git+https://github.com/cta-observatory/ctapipe-extra
- pip install git+https://github.com/cta-observatory/ctapipe
- pip install numpy
- pip install astropy
